services:
  db:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./db_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

  backend:
    container_name: fastapi
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/minecraft-tool:rw
    ports:
      - 8000:8000

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
